services:
  crash-test:
    build: .
    environment:
      - JAVA_TOOL_OPTIONS=-XX:+CreateCoredumpOnCrash -XX:ErrorFile=/core-dumps/hs_err_pid%p.log
    ports:
      - "8080:8080"
    volumes:
      - ./core-dumps:/core-dumps
